server:
  port: 8080

spring:
  aplication:
    name: ms-usuarios
  security:
    authorize:
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios
    username: postgres
    password: postgres

appDescription: "Usuario"
appVersion: "1.0.0"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true


empleado:
  restaurante:
    url: "http://localhost:8081"